-- Insert initial destinations data
insert into public.destinations (
    name,
    city,
    province,
    type,
    latitude,
    longitude,
    hours,
    duration,
    description,
    image,
    price,
    rating,
    transportation
) values
    (
        'Candi Prambanan',
        'Sleman',
        'DI Yogyakarta',
        'Arsitektur & Warisan Sejarah',
        -7.7522,
        110.4917,
        ('06:00', '17:00'),
        90,
        'Candi Prambanan adalah kompleks candi Hindu terbesar di Indonesia yang dibangun pada abad ke-9. Candi ini didedikasikan untuk Trimurti: Brahma, Vishnu, dan Shiva. Prambanan telah ditetapkan sebagai Situs Warisan Dunia UNESCO.',
        '/culture-uploads/Candi Prambanan.jpg',
        50000,
        4.7,
        array['Bus', 'Taksi', 'Rental Mobil']
    ),
    (
        'Desa Adat Penglipuran',
        'Bangli',
        'Bali',
        'Kehidupan Adat & Arsitektur',
        -8.4095,
        115.3660,
        ('08:00', '17:00'),
        60,
        'Desa Adat Penglipuran adalah salah satu desa tradisional di Bali yang masih mempertahankan gaya arsitektur dan tata ruang khas Bali. Desa ini terkenal dengan jalan utamanya yang bersih dan tertata rapi, serta rumah-rumah tradisional yang seragam.',
        '/culture-uploads/Desa Adat Penglipuran.jpeg',
        30000,
        4.5,
        array['Motor', 'Rental Mobil', 'Tour Guide']
    ),
    (
        'Tana Toraja',
        'Tana Toraja',
        'Sulawesi Selatan',
        'Tradisi Kematian & Arsitektur',
        -3.0000,
        120.0000,
        ('08:00', '17:00'),
        180,
        'Tana Toraja terkenal dengan upacara pemakaman yang elaborate dan rumah-rumah tradisional berbentuk perahu (Tongkonan). Tradisi dan budaya Toraja menawarkan pengalaman budaya yang unik dan mendalam bagi pengunjung.',
        '/culture-uploads/Tana Toraja.png',
        25000,
        4.8,
        array['Bus', 'Rental Mobil', 'Pesawat ke Makassar']
    ),
    (
        'Kampung Batik Trusmi',
        'Cirebon',
        'Jawa Barat',
        'Kerajinan Tradisional',
        -6.7333,
        108.5667,
        ('08:00', '17:00'),
        60,
        'Kampung Batik Trusmi adalah pusat kerajinan batik di Cirebon. Pengunjung dapat melihat proses pembuatan batik secara langsung dan berbelanja berbagai produk batik khas Cirebon dengan motif yang unik.',
        '/culture-uploads/Batik Trusmi.png',
        10000,
        4.3,
        array['Angkot', 'Taksi', 'Kereta ke Cirebon']
    ),
    (
        'Keraton Yogyakarta',
        'Yogyakarta',
        'DI Yogyakarta',
        'Warisan Kerajaan & Seni Pertunjukan',
        -7.8056,
        110.3647,
        ('08:30', '14:00'),
        60,
        'Keraton Yogyakarta adalah istana resmi Kesultanan Ngayogyakarta Hadiningrat. Kompleks keraton ini menampilkan arsitektur Jawa tradisional dan menyimpan berbagai benda bersejarah. Pada waktu tertentu, pengunjung dapat menyaksikan pertunjukan tari dan musik tradisional.',
        '/culture-uploads/Keraton Yogyakarta.jpg',
        15000,
        4.6,
        array['Becak', 'Andong', 'Bus Trans Jogja']
    ),
    (
        'Desa Adat Wae Rebo',
        'Manggarai',
        'Nusa Tenggara Timur',
        'Kehidupan Adat & Arsitektur',
        -8.7680,
        120.2838,
        ('24 jam', '24 jam'),
        720,
        'Desa Wae Rebo terletak di ketinggian 1.200 meter di atas permukaan laut dan terkenal dengan rumah adat berbentuk kerucut ''Mbaru Niang''. Untuk mencapai desa ini, pengunjung harus melakukan hiking selama 3-4 jam.',
        '/culture-uploads/Desa Adat Wae Rebo.jpg',
        350000,
        4.9,
        array['Rental Mobil', 'Pemandu Trek']
    ),
    (
        'Candi Borobudur',
        'Magelang',
        'Jawa Tengah',
        'Arsitektur & Warisan Sejarah',
        -7.6079,
        110.2038,
        ('06:00', '17:00'),
        90,
        'Candi Borobudur adalah candi Buddha terbesar di dunia yang dibangun pada abad ke-9. Monumen ini memiliki 2.672 panel relief dan 504 patung Buddha. Borobudur adalah Situs Warisan Dunia UNESCO dan menjadi salah satu tujuan wisata paling populer di Indonesia.',
        '/culture-uploads/Candi Borobudur.png',
        50000,
        4.8,
        array['Bus', 'Taksi', 'Tour']
    ),
    (
        'Kampung Naga',
        'Tasikmalaya',
        'Jawa Barat',
        'Kehidupan Adat & Arsitektur',
        -7.3510,
        107.9560,
        ('08:00', '17:00'),
        60,
        'Kampung Naga adalah desa adat yang masyarakatnya masih mempertahankan adat istiadat dan tradisi leluhur. Rumah-rumah di desa ini semuanya menghadap ke utara atau selatan dan terbuat dari bahan-bahan alami.',
        '/culture-uploads/Kampung Naga.jpg',
        15000,
        4.4,
        array['Angkot', 'Ojek']
    ),
    (
        'Istana Maimun',
        'Medan',
        'Sumatera Utara',
        'Warisan Kerajaan & Arsitektur',
        3.5753,
        98.6839,
        ('08:00', '17:00'),
        45,
        'Istana Maimun adalah istana Kesultanan Deli yang dibangun pada tahun 1888. Arsitektur istana menggabungkan gaya Melayu, Islam, Spanyol, India, dan Italia. Di dalam istana terdapat pajangan benda-benda bersejarah peninggalan Kesultanan Deli.',
        '/culture-uploads/Istana Maimun.jpg',
        10000,
        4.2,
        array['Becak', 'Taksi', 'Bus Kota']
    ),
    (
        'Desa Tenganan Pegringsingan',
        'Karangasem',
        'Bali',
        'Kehidupan Adat & Kerajinan',
        -8.5000,
        115.5833,
        ('08:00', '17:00'),
        60,
        'Desa Tenganan Pegringsingan adalah salah satu desa Bali Aga (Bali asli) yang masih mempertahankan tradisi dan gaya hidup kuno. Desa ini terkenal dengan kerajinan kain gringsing double ikat yang sangat langka dan berharga.',
        '/culture-uploads/Desa Tenganan Pegringsingan.jpg',
        20000,
        4.5,
        array['Rental Motor', 'Taksi', 'Tour']
    );