name: Block commits containing env files

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  forbid-env:
    name: Fail PR if .env files are changed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect forbidden env file changes
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}
        run: |
          set -e
          echo "Base ref: $BASE_REF"
          # Ensure we have the base branch
          git fetch origin "$BASE_REF" --depth=1 || true

          # List changed files between base and the PR HEAD
          CHANGED=$(git diff --name-only "origin/$BASE_REF...HEAD")
          echo "Changed files:\n$CHANGED"

          # Pattern: .env, .env.local, .env.* (any file starting with .env)
          echo "$CHANGED" | grep -E "(^|/)\.env($|/)|(^|/)\.env\..*" >/dev/null 2>&1 && {
            echo "\nERROR: Pull request modifies files that look like environment files (.env, .env.local, .env.*).";
            echo "To fix: remove those files from the commit, keep secrets out of the repo, and use repository secrets or Vercel project variables.";
            echo "You can run locally: git rm --cached .env && git commit --amend --no-edit";
            exit 1;
          } || echo "No .env-like files changed. OK."
